spring.application.name=projectjava
spring.web.error.include-stacktrace=never
# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/learnjava
spring.datasource.username=postgres
spring.datasource.password=Nha1213

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8083
